{% set name = "jaxtyping" %}
{% set version = "0.3.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jaxtyping-{{ version }}.tar.gz
  sha256: 8003cfd16ba2ad9b47fdda1d982a575299a81ddfc7997ad0e917c87a0897ea86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - wadler-lindig >=0.1.3

test:
  imports:
    - jaxtyping
  commands:
    - pip check
  requires:
    - pip
    - python >={{ python_min }}

about:
  home: https://github.com/google/jaxtyping
  summary: Type annotations and runtime checking for shape and dtype of JAX arrays, and PyTrees.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - ngam
    - iamthebot
