{% set name = "jaxtyping" %}
{% set version = "0.2.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaxtyping-{{ version }}.tar.gz
  sha256: cc5bef7d1eb757b442710ac17aa4e62d2fdf47e4b3be04c3ebf808f84b7bcd77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.20.0
    - typeguard >=2.13.3
    - typing-extensions >=3.7.4.1

test:
  imports:
    - jaxtyping
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jaxtyping
  summary: Type annotations and runtime checking for shape and dtype of JAX arrays, and PyTrees.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
