{% set name = "jaxtyping" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jaxtyping-{{ version }}.tar.gz
  sha256: 38bb47dc090696ed5959bf3c7e8659036d3cd2643f882c9208d5d9644ae789fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
  run:
    - python >=3.9
    - typeguard ==2.13.3

test:
  imports:
    - jaxtyping
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jaxtyping
  summary: Type annotations and runtime checking for shape and dtype of JAX arrays, and PyTrees.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - ngam
